import nodemailer from 'nodemailer';
import 'dotenv/config';

// Create a transporter object using your email service's SMTP settings.
// These should be defined in your .env file.
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: process.env.EMAIL_PORT,
  secure: process.env.EMAIL_SECURE === 'true', // true for 465, false for other ports
  auth: {
    user: process.env.EMAIL_USER, // Should be "apikey" for SendGrid
    pass: process.env.EMAIL_PASS,
  },
});

// The function now accepts the full verificationLink generated by Firebase.
const sendVerificationEmail = async (userEmail, verificationLink) => {
  
  const mailOptions = {
    // UPDATED: The 'from' address now uses your verified SendGrid Sender Identity.
    from: `"Stage Scout" <stagescout.official@gmail.com>`,
    to: userEmail,
    subject: 'Stage Scout Email Verification',
    html: `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #667eea;">Welcome to Stage Scout!</h2>
        <p>Thank you for registering. Please verify your email address by clicking the button below.</p>
        <a href="${verificationLink}" style="display: inline-block; padding: 10px 20px; margin: 20px 0; font-size: 16px; color: white; background-color: #667eea; text-decoration: none; border-radius: 5px;">
          Verify Email Address
        </a>
        <p>If you did not create an account, no further action is required.</p>
        <p style="font-size: 12px; color: #999;">If the button doesn't work, you can copy and paste this link into your browser: <br/>${verificationLink}</p>
        <hr style="border: 0; border-top: 1px solid #eee; margin-top: 20px;">
        <p style="font-size: 12px; color: #999;">This email was sent from Stage Scout. Please do not reply to this email.</p>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`Verification email sent to ${userEmail}`);
  } catch (error) {
    console.error(`Failed to send verification email to ${userEmail}:`, error);
    // It's important to handle this error, perhaps by logging it to a more persistent service.
  }
};

export { sendVerificationEmail };
